version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "telovpn"
      POSTGRES_USER: "telovpn"
      POSTGRES_PASSWORD: "password1235"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - telo-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "russiancmo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  telo-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge